{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.samsonovaa",
    "module": "logging-starter",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1205,
          "sha512": "67ce80cfac244468ec697e5d96f9f4818225474c3a9c017e52d3fb47bbc5717e6b7499bf25077eb463c4ccf5ecdc06205a7a5ffe680e707038376e2f92a5381d",
          "sha256": "2309ae34f3d65c3e4929ab24697216c8117f358637c853aab5c5ec686a87ce74",
          "sha1": "07b20dede443ae30befbfe672875f751a793bd24",
          "md5": "43c5e5f1f843399a4bc35f7345ecb02f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.0-SNAPSHOT.jar",
          "url": "logging-starter-1.0-SNAPSHOT.jar",
          "size": 1205,
          "sha512": "67ce80cfac244468ec697e5d96f9f4818225474c3a9c017e52d3fb47bbc5717e6b7499bf25077eb463c4ccf5ecdc06205a7a5ffe680e707038376e2f92a5381d",
          "sha256": "2309ae34f3d65c3e4929ab24697216c8117f358637c853aab5c5ec686a87ce74",
          "sha1": "07b20dede443ae30befbfe672875f751a793bd24",
          "md5": "43c5e5f1f843399a4bc35f7345ecb02f"
        }
      ]
    }
  ]
}
